apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "nginx-deployment-v1.labels" . | nindent 4 }}
  name: {{ template "nginx-deployment-v1.fullname" . }}
  namespace: default
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels: {{- include "nginx-deployment-v1.matchLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels: {{- include "nginx-deployment-v1.labels" . | nindent 8 }}
    spec:
      containers:
      {{- if .Values.env }}
        env: {{ toYaml .Values.env| nindent 8 }}
	  	{{- end }}
        image: {{ .Values.image.image }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent"}}
      {{- if .Values.prob.livenessProbe }}
        livenessProbe: {{ toYaml .Values.prob.livenessProbe | nindent 8 }}
	  	{{- end }}
        name: nginx
      {{- if .Values.ports }}
        ports: {{ toYaml .Values.ports | nindent 8 }}
	  	{{- end }}
      {{- if .Values.prob.readinessProbe }}
        readinessProbe: {{ toYaml .Values.prob.readinessProbe | nindent 8 }}
	  	{{- end }}
      {{- if .Values.resource }}
        resources: {{ toYaml .Values.resource | nindent 10 }}
	  	{{- end }}
      {{- if .Values.image.imagePullSecrets }}
        imagePullSecrets: {{ toYaml .Values.image.imagePullSecrets | nindent 8 }}
	  	{{- end }}
